version: '3.7'

services:
  redis:
    image: redis:7.0.11
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - /Users/shawn/Docker/volumes/datadir/redis/rd:/data