version: '3.8'

services:
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - $HOME/Docker/volumes/datadir/redis/rd:/data